(function(){'use strict';
let generation=0;const actor=()=>{const a=window.portalSession?.identity();return window.portalSession?.connected()&&a?.code?JSON.stringify([a.kind||'employee',a.code]):''};
function formHTML(saved={}){const months=saved.rows||Array.from({length:12},(_,i)=>({month:new Date().getFullYear()+'-'+String(i+1).padStart(2,'0'),bill:'',paid:'',lease1:'',lease2:'',lease3:'',labor:''}));return `<section class="panel"><h2>現場の利益管理表</h2><p class="notice">社長権限で共有保存します。日報・支払い表からの自動取り込みは未接続です。固定費12,000円・給与26,000円は未設定時の参考初期値です。実際の単価と税込・税抜の扱いを確認して入力してください。</p><form id="profitDraft"><div class="row"><label>請負金額（円）<input name="contract" type="number" min="0" value="${esc(saved.contract||'')}"></label><label>1人工の固定費（円）<input name="fixed" type="number" min="0" value="${esc(saved.fixed??12000)}"></label><label>1人工の給与単価（円）<input name="wage" type="number" min="0" value="${esc(saved.wage??26000)}"></label></div><div class="stock-scroll"><table class="stock-sheet" style="min-width:1250px"><thead><tr>${['月','請求額','入金額','未入金','リース①','リース②','リース③','人工','請求−リース','固定費控除後','給与控除後','入金ベース残額'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${months.map((r,i)=>`<tr data-profit-row>${['month','bill','paid','lease1','lease2','lease3','labor'].map((k,j)=>`${j===3?'<td data-calc="unpaid"></td>':''}<td><input aria-label="${i+1}行目 ${k}" data-field="${k}" type="${k==='month'?'month':'number'}" ${k==='month'?'':'min="0" step="any"'} value="${esc(r[k])}" style="width:${k==='month'?130:100}px"></td>`).join('')}<td data-calc="net"></td><td data-calc="fixed"></td><td data-calc="profit"></td><td data-calc="cash"></td></tr>`).join('')}</tbody><tfoot><tr><th colspan="11">給与控除後残額 合計（請求ベース）</th><td id="profitSum"></td></tr></tfoot></table></div><p>請求ベース＝請求−リース−人工×固定費単価−人工×給与単価。入金ベースは請求額を入金額に置き換えます。未入力は計算上0として扱います。</p><button class="primary" type="submit">入力内容を共有先に保存</button><span id="profitSaved" role="status"></span></form></section>`}
window.profitPanel=sid=>'<section class="panel" id="sharedProfit" data-site="'+esc(String(sid))+'"><h2>現場の利益管理表</h2><p data-profit-load role="status">社長権限と保存内容を確認中…</p></section>';
function wireForm(f,key,revision,owner,ticket){
 const calculate=()=>{let sum=0;f.querySelectorAll('[data-profit-row]').forEach(row=>{const val=k=>Number(row.querySelector('[data-field="'+k+'"]').value)||0,lease=val('lease1')+val('lease2')+val('lease3'),cost=val('labor')*Number(f.elements.fixed.value),pay=val('labor')*Number(f.elements.wage.value),net=val('bill')-lease,result={unpaid:val('bill')-val('paid'),net,fixed:net-cost,profit:net-cost-pay,cash:val('paid')-lease-cost-pay};sum+=result.profit;for(const [k,n]of Object.entries(result)){const c=row.querySelector('[data-calc="'+k+'"]');c.textContent=n.toLocaleString();c.style.color=n<0?'#b32626':'#175b45'}});$('profitSum').textContent=sum.toLocaleString()+'円'};f.oninput=calculate;calculate();
 const feedback=f.querySelector('#profitSaved'),button=f.querySelector('[type=submit]');let saving=false;const alive=()=>f.isConnected&&actor()===owner&&generation===ticket;const opKey=siteSharedStore.key('__company__','利益管理',key);const compare=document.createElement('button');compare.type='button';compare.className='secondary';compare.textContent='最新の内容と比較';compare.hidden=true;f.append(compare);const comparison=document.createElement('section');f.append(comparison);const snapshot=()=>({contract:f.elements.contract.value,fixed:f.elements.fixed.value,wage:f.elements.wage.value,rows:[...f.querySelectorAll('[data-profit-row]')].map(row=>Object.fromEntries([...row.querySelectorAll('[data-field]')].map(i=>[i.dataset.field,i.value])))});
 compare.onclick=async()=>{if(saving)return;compare.disabled=true;comparison.replaceChildren();try{const rows=await siteSharedStore.list('__company__','利益管理'),pending=(await siteSharedStore.pending()).find(x=>x.key===opKey);if(!alive())return;const latest=rows.find(r=>r.id===key),latestRevision=Number(latest?.revision||0),input=snapshot(),saved=latest?.payload||{},requestId=pending?.requestId;const labels={contract:'請負金額',fixed:'固定費単価',wage:'給与単価'};let table='<h3>保存済みの最新版と今回の入力</h3><p>最新版 第'+latestRevision+'版を確認し、下のボタンで今回の入力を保存し直します。</p><div style="overflow:auto"><table><thead><tr><th>項目</th><th>保存済みの最新版</th><th>今回の入力</th></tr></thead><tbody>';for(const [k,label]of Object.entries(labels))table+='<tr><th>'+label+'</th><td>'+esc(saved[k]||'未入力')+'</td><td>'+esc(input[k]||'未入力')+'</td></tr>';const fields={month:'月',bill:'請求',paid:'入金',lease1:'リース①',lease2:'リース②',lease3:'リース③',labor:'人工'};for(let i=0;i<Math.max(saved.rows?.length||0,input.rows.length);i++)for(const [k,label]of Object.entries(fields))table+='<tr><th>'+(i+1)+'行目 '+label+'</th><td>'+esc(saved.rows?.[i]?.[k]||'未入力')+'</td><td>'+esc(input.rows[i]?.[k]||'未入力')+'</td></tr>';comparison.innerHTML=table+'</tbody></table></div>';const resave=document.createElement('button');resave.type='button';resave.className='primary';resave.textContent='この入力で保存し直す';comparison.append(resave);resave.onclick=async()=>{if(saving||!alive())return;if(JSON.stringify(snapshot())!==JSON.stringify(input)){feedback.textContent='入力が変わりました。最新の内容ともう一度比較してください。';comparison.replaceChildren();return}resave.disabled=true;compare.disabled=true;button.disabled=true;saving=true;let handed=false;const locked=[...f.querySelectorAll('input')];locked.forEach(i=>i.disabled=true);try{const now=(await siteSharedStore.pending()).find(x=>x.key===opKey);if(!alive())return;if((now?.requestId||null)!==(requestId||null))throw Error('未送信記録が変わりました。もう一度比較してください');if(requestId)await siteSharedStore.resolvePending(opKey,requestId);if(!alive())return;revision=latestRevision;comparison.replaceChildren();saving=false;locked.forEach(i=>i.disabled=false);handed=true;f.requestSubmit();}catch(e){if(alive()){feedback.textContent=e.message+' 入力はこの画面に残しています。';comparison.replaceChildren();}}finally{if(!handed){saving=false;if(alive()){button.disabled=false;locked.forEach(i=>i.disabled=false);}}if(alive())compare.disabled=false;}};}catch(e){if(alive())feedback.textContent=e.message+' 入力はこの画面に残しています。';}finally{if(alive())compare.disabled=false;}};
 f.onsubmit=async e=>{e.preventDefault();if(saving)return;saving=true;button.disabled=true;feedback.textContent='保存中…';
 const value={contract:f.elements.contract.value,fixed:f.elements.fixed.value,wage:f.elements.wage.value,rows:[...f.querySelectorAll('[data-profit-row]')].map(row=>Object.fromEntries([...row.querySelectorAll('[data-field]')].map(i=>[i.dataset.field,i.value])))};
 const inputs=[...f.querySelectorAll('input')];inputs.forEach(i=>i.disabled=true);
 try{if(actor()!==owner||generation!==ticket)throw Error('ログインが変わりました。開き直してください');const result=await siteSharedStore.save('__company__','利益管理',key,value,{revision});if(!f.isConnected||actor()!==owner||generation!==ticket)return;revision=Number(result.revision);feedback.textContent='共有先に保存しました';compare.hidden=true;comparison.replaceChildren();}
 catch(e){if(f.isConnected&&actor()===owner&&generation===ticket){feedback.textContent=e.message+' 入力はこの画面に残しています。';compare.hidden=false;}}
 finally{saving=false;if(f.isConnected){button.disabled=false;inputs.forEach(i=>i.disabled=false);}}
 };
}
async function mount(){const box=document.getElementById('sharedProfit');if(!box||box.dataset.bound)return;box.dataset.bound='1';const owner=actor(),ticket=generation,sid=box.dataset.site,status=box.querySelector('[data-profit-load]');
 if(!owner||!window.siteSharedStore){status.textContent='ポータルのログイン確認後、社長権限で表示できます。';return}
 try{const key=sitePortalSiteKey(sid),rows=await siteSharedStore.list('__company__','利益管理');if(!box.isConnected||actor()!==owner||generation!==ticket)return;const row=rows.find(r=>r.id===key);box.innerHTML=formHTML(row?.payload||{});wireForm(box.querySelector('#profitDraft'),key,Number(row?.revision||0),owner,ticket);}
 catch(e){if(box.isConnected&&actor()===owner&&generation===ticket){status.textContent=e.message;const b=document.createElement('button');b.className='secondary';b.textContent='もう一度確認する';b.onclick=()=>{delete box.dataset.bound;b.remove();mount()};box.append(b)}}
}
window.addEventListener('portal-session-ready',()=>{generation++;const box=document.getElementById('sharedProfit');if(box){const sid=box.dataset.site;box.outerHTML=window.profitPanel(sid);mount()}});
window.addEventListener('DOMContentLoaded',()=>{new MutationObserver(mount).observe(document.getElementById('app'),{childList:true,subtree:true});mount();window.appSharedFeatures={...window.appSharedFeatures,'利益管理':true}});
})();

